import json

d={#English
    'move':"f1 f1",
    'follow me':"f1 f2",
    'charge':"f1 f3",
    'advance':"f1 f4",
    'fall back':"f1 f5",
    'stop':"f1 f6",
    'retreat':"f1 f7",
    'line formation':"f2 f1",
    'Shield wall':"f2 f2",
    'loose formation':"f2 f3",
    'circle formation':"f2 f4",
    'square formation':"f2 f5",
    'v formation':"f2 f2",
    'column formation':"f2 f7",
    'scatter':"f2 f8",
    'toggle fire':"f4",
    'toggle mount':"f5",
    'toggle delegation':"f6",
    'face that way':"f7",
    'shield up':"f8",
    'line up':"f1 f9",
    'refresh':"f5",
    'shutdown':"f4",
    
    #selection
    'infantry':"1",
    'arrows':"2",
    'cavalry':"3",
    'everyone':"4",
    'group 1':"1",
    'group 2':"2",
    'group 3':"3",
    'group 4':"4",

    
    #Hindi
    'यहां पर':"f1 f1",
    'मेरे पीछे':"f1 f2",
    'आक्रमण':"f1 f3",
    'हर हर महादेव':"f1 f3",
    'आगे बढ़ो':"f1 f4",
    'वापस':"f1 f5",
    'रुको':"f1 f6",
    'विसर्जन':"f1 f7",
    'सीधा गठन':"f2 f1",
    'रक्षा दीवार':"f2 f2",
    'ढीला गठन':"f2 f3",
    'मंडली घटन':"f2 f4",
    'वर्ग गठन':"f2 f5",
    'त्रिकोण गठन':"f2 f2",
    'आयात गठन':"f2 f7",
    'विस्तार':"f2 f8",
    'तलवार स्थिति':"f4",
    'सवारी स्थिति':"f5",
    'प्रतिनिधि':"f6",
    'उस तरफ':"f7",
    'सतर्क':"f8",
    'पंक्ति बनाओ':"f1 f9",
    #selection
    'पैदल सेना':"1",
    'निशानेबाज':"2",
    'घुड़सवार':"3",
    'सेना':"4",
    'प्रथम पलटन':"1",
    'द्वितीय पलटन':"2",
    'तृतीय पलटन':"3",
    'चौथे पलटन':"4",
    }

with open('dict.json', 'w') as f:
    json.dump(d, f)
